### ISSUE TITLE
无libpq.lib

### ISSUE THREAD

**Issue by ariagecheney** [yez730/meli#1]
1 首先是找不到libpq.lib
2 我把postgrep安装以后的lib文件夹下的libpq.lib复制到vs2022的x64的lib下，
3 编译通过，运行报错，STATUS_DLL 未找到。

**Comment by yez730** [comment]
1. 添加libpg相关的目录到`PATH`环境变量，如 `C:\Program Files\PostgreSQL\15\lib` 和 `C:\Program Files\PostgreSQL\15\bin` 。
2. 重新build之前，先clean一下（若失败可能需要重启机器）
3. 运行之前，先要用[diesel_cli](https://diesel.rs/guides/getting-started#installing-diesel-cli)初始化数据库。运行`cargo install diesel_cli --no-default-features --features postgres
`以安装`diesel_cli`，再在项目目录下运行`diesel setup`。

不知道你这里的STATUS_DLL 是个啥错误，libpg配置正确，没有数据库就运行，显示的应该是diesel提供的类似`error: process didn't exit successfully: .... (exit code: 3) `之类的错误。

**Comment by ariagecheney** [comment]
1.  安装windows zip版本postgresql;  配置好Path
`D:\devkit\pgsql\postgresql-15.1-1-windows-x64-binaries\pgsql\bin\`  和 `D:\devkit\pgsql\postgresql-15.1-1-windows-x64-binaries\pgsql\lib\` 
2. 运行`cargo install diesel_cli --no-default-features --features postgres` , OK, 但是在cmd里执行`diesel` , 会提示`no  libpq.dll  found`
3.  已cargo clean , 随后cargo build ; OK
4.  在pgsql的`bin\` 下, 执行`pg_ctl.exe  -D ../data -l ../logs/log start` 
5.在项目的当前目录下执行`diesel setup` , OK
```
Creating database: meli
Running migration 2022-09-08-101419_create_permissions
Running migration 2022-09-08-113739_create_sessions
Running migration 2022-09-08-114851_create_users
Running migration 2022-09-08-122121_create_members
Running migration 2022-09-17-102857_create_roles
Running migration 2022-09-17-103206_create_barbers
Running migration 2022-09-17-103315_create_merchants
Running migration 2022-09-17-111230_init_data
Running migration 2022-09-17-122649_create_login_infos
Running migration 2022-09-17-123853_create_password_login_providers
Running migration 2022-10-02-094754_create_order
Running migration 2022-10-02-094812_create_recharge_records
Running migration 2022-10-03-081809_create_service_types
Running migration 2022-10-03-082806_create_merchant_members
Running migration 2022-10-19-164218_add_some_fields
Running migration 2022-10-30-092557_临时方案_add_merchant_member_fields
````
6. 执行cargo run  , 显示:  
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target\debug\meli-backend.exe`
error: process didn't exit successfully: `target\debug\meli-backend.exe` (exit code: 3)
````

**Comment by ariagecheney** [comment]
> 1. 安装windows zip版本postgresql;  配置好Path
>    `D:\devkit\pgsql\postgresql-15.1-1-windows-x64-binaries\pgsql\bin\`  和 `D:\devkit\pgsql\postgresql-15.1-1-windows-x64-binaries\pgsql\lib\`
> 2. 运行`cargo install diesel_cli --no-default-features --features postgres` , OK, 但是在cmd里执行`diesel` , 会提示`no  libpq.dll  found`
> 3. 已cargo clean , 随后cargo build ; OK
> 4. 在pgsql的`bin\` 下, 执行`pg_ctl.exe  -D ../data -l ../logs/log start`
>    5.在项目的当前目录下执行`diesel setup` , OK
> 
> ```
> Creating database: meli
> Running migration 2022-09-08-101419_create_permissions
> Running migration 2022-09-08-113739_create_sessions
> Running migration 2022-09-08-114851_create_users
> Running migration 2022-09-08-122121_create_members
> Running migration 2022-09-17-102857_create_roles
> Running migration 2022-09-17-103206_create_barbers
> Running migration 2022-09-17-103315_create_merchants
> Running migration 2022-09-17-111230_init_data
> Running migration 2022-09-17-122649_create_login_infos
> Running migration 2022-09-17-123853_create_password_login_providers
> Running migration 2022-10-02-094754_create_order
> Running migration 2022-10-02-094812_create_recharge_records
> Running migration 2022-10-03-081809_create_service_types
> Running migration 2022-10-03-082806_create_merchant_members
> Running migration 2022-10-19-164218_add_some_fields
> Running migration 2022-10-30-092557_临时方案_add_merchant_member_fields
> ```
> 
> 6. 执行cargo run  , 显示:
> 
> ```
>     Finished dev [unoptimized + debuginfo] target(s) in 0.19s
>      Running `target\debug\meli-backend.exe`
> error: process didn't exit successfully: `target\debug\meli-backend.exe` (exit code: 3)
> ```

检查:
1. 查看postgresql运行语法
```
netstat -ano | findstr 5432
  TCP    10.20.52.54:54320      47.105.216.175:443     TIME_WAIT       0
  TCP    10.20.52.54:54322      47.104.37.220:443      TIME_WAIT       0
  TCP    10.20.52.54:54327      180.101.49.13:443      ESTABLISHED     19120
  TCP    127.0.0.1:5432         0.0.0.0:0              LISTENING       11304
  TCP    127.0.0.1:31181        127.0.0.1:54323        ESTABLISHED     19120
  TCP    127.0.0.1:54321        127.0.0.1:31181        TIME_WAIT       0
  TCP    127.0.0.1:54323        127.0.0.1:31181        ESTABLISHED     14656
  TCP    127.0.0.1:54325        127.0.0.1:31181        TIME_WAIT       0
  TCP    127.0.0.1:54326        127.0.0.1:31181        TIME_WAIT       0
  TCP    [::1]:5432             [::]:0                 LISTENING       11304
```
2.  再次执行cargo clean , 同时手动删除当前项目目录下的target/   ;
3. cargo build  ;   编译OK
```
PS D:\coding\rustProj\meli> cargo build 
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.3
......
   Compiling axum v0.6.0-rc.2                                                                                                                                                                                                          
   Compiling meli-backend v0.1.0 (D:\coding\rustProj\meli)                                                                                                                                                                             
    Finished dev [unoptimized + debuginfo] target(s) in 1m 37s      
```
4. cargo run  如下:
```
PS D:\coding\rustProj\meli> cargo run 
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target\debug\meli-backend.exe`
error: process didn't exit successfully: `target\debug\meli-backend.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
```

**Comment by ariagecheney** [comment]
> 1. 安装windows zip版本postgresql;  配置好Path
>    `D:\devkit\pgsql\postgresql-15.1-1-windows-x64-binaries\pgsql\bin\`  和 `D:\devkit\pgsql\postgresql-15.1-1-windows-x64-binaries\pgsql\lib\`
> 2. 运行`cargo install diesel_cli --no-default-features --features postgres` , OK, 但是在cmd里执行`diesel` , 会提示`no  libpq.dll  found`
> 3. 已cargo clean , 随后cargo build ; OK
> 4. 在pgsql的`bin\` 下, 执行`pg_ctl.exe  -D ../data -l ../logs/log start`
>    5.在项目的当前目录下执行`diesel setup` , OK
> 
> ```
> Creating database: meli
> Running migration 2022-09-08-101419_create_permissions
> Running migration 2022-09-08-113739_create_sessions
> Running migration 2022-09-08-114851_create_users
> Running migration 2022-09-08-122121_create_members
> Running migration 2022-09-17-102857_create_roles
> Running migration 2022-09-17-103206_create_barbers
> Running migration 2022-09-17-103315_create_merchants
> Running migration 2022-09-17-111230_init_data
> Running migration 2022-09-17-122649_create_login_infos
> Running migration 2022-09-17-123853_create_password_login_providers
> Running migration 2022-10-02-094754_create_order
> Running migration 2022-10-02-094812_create_recharge_records
> Running migration 2022-10-03-081809_create_service_types
> Running migration 2022-10-03-082806_create_merchant_members
> Running migration 2022-10-19-164218_add_some_fields
> Running migration 2022-10-30-092557_临时方案_add_merchant_member_fields
> ```
> 
> 6. 执行cargo run  , 显示:
> 
> ```
>     Finished dev [unoptimized + debuginfo] target(s) in 0.19s
>      Running `target\debug\meli-backend.exe`
> error: process didn't exit successfully: `target\debug\meli-backend.exe` (exit code: 3)
> ```

检查:
1. 查看postgresql运行语法
```
netstat -ano | findstr 5432
  TCP    10.20.52.54:54320      47.105.216.175:443     TIME_WAIT       0
  TCP    10.20.52.54:54322      47.104.37.220:443      TIME_WAIT       0
  TCP    10.20.52.54:54327      180.101.49.13:443      ESTABLISHED     19120
  TCP    127.0.0.1:5432         0.0.0.0:0              LISTENING       11304
  TCP    127.0.0.1:31181        127.0.0.1:54323        ESTABLISHED     19120
  TCP    127.0.0.1:54321        127.0.0.1:31181        TIME_WAIT       0
  TCP    127.0.0.1:54323        127.0.0.1:31181        ESTABLISHED     14656
  TCP    127.0.0.1:54325        127.0.0.1:31181        TIME_WAIT       0
  TCP    127.0.0.1:54326        127.0.0.1:31181        TIME_WAIT       0
  TCP    [::1]:5432             [::]:0                 LISTENING       11304
```
2.  再次执行cargo clean , 同时手动删除当前项目目录下的target/   ;
3. cargo build  ;   编译OK
```
PS D:\coding\rustProj\meli> cargo build 
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.3
......
   Compiling axum v0.6.0-rc.2                                                                                                                                                                                                          
   Compiling meli-backend v0.1.0 (D:\coding\rustProj\meli)                                                                                                                                                                             
    Finished dev [unoptimized + debuginfo] target(s) in 1m 37s      
```
4. cargo run  如下:
```
PS D:\coding\rustProj\meli> cargo run 
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target\debug\meli-backend.exe`
error: process didn't exit successfully: `target\debug\meli-backend.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
```

**Comment by ariagecheney** [comment]
> > 1. 安装windows zip版本postgresql;  配置好Path
> >    `D:\devkit\pgsql\postgresql-15.1-1-windows-x64-binaries\pgsql\bin\`  和 `D:\devkit\pgsql\postgresql-15.1-1-windows-x64-binaries\pgsql\lib\`
> > 2. 运行`cargo install diesel_cli --no-default-features --features postgres` , OK, 但是在cmd里执行`diesel` , 会提示`no  libpq.dll  found`
> > 3. 已cargo clean , 随后cargo build ; OK
> > 4. 在pgsql的`bin\` 下, 执行`pg_ctl.exe  -D ../data -l ../logs/log start`
> >    5.在项目的当前目录下执行`diesel setup` , OK
> > 
> > ```
> > Creating database: meli
> > Running migration 2022-09-08-101419_create_permissions
> > Running migration 2022-09-08-113739_create_sessions
> > Running migration 2022-09-08-114851_create_users
> > Running migration 2022-09-08-122121_create_members
> > Running migration 2022-09-17-102857_create_roles
> > Running migration 2022-09-17-103206_create_barbers
> > Running migration 2022-09-17-103315_create_merchants
> > Running migration 2022-09-17-111230_init_data
> > Running migration 2022-09-17-122649_create_login_infos
> > Running migration 2022-09-17-123853_create_password_login_providers
> > Running migration 2022-10-02-094754_create_order
> > Running migration 2022-10-02-094812_create_recharge_records
> > Running migration 2022-10-03-081809_create_service_types
> > Running migration 2022-10-03-082806_create_merchant_members
> > Running migration 2022-10-19-164218_add_some_fields
> > Running migration 2022-10-30-092557_临时方案_add_merchant_member_fields
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 6. 执行cargo run  , 显示:
> > 
> > ```
> >     Finished dev [unoptimized + debuginfo] target(s) in 0.19s
> >      Running `target\debug\meli-backend.exe`
> > error: process didn't exit successfully: `target\debug\meli-backend.exe` (exit code: 3)
> > ```
> 
> 检查:
> 
> 1. 查看postgresql运行语法
> 
> ```
> netstat -ano | findstr 5432
>   TCP    10.20.52.54:54320      47.105.216.175:443     TIME_WAIT       0
>   TCP    10.20.52.54:54322      47.104.37.220:443      TIME_WAIT       0
>   TCP    10.20.52.54:54327      180.101.49.13:443      ESTABLISHED     19120
>   TCP    127.0.0.1:5432         0.0.0.0:0              LISTENING       11304
>   TCP    127.0.0.1:31181        127.0.0.1:54323        ESTABLISHED     19120
>   TCP    127.0.0.1:54321        127.0.0.1:31181        TIME_WAIT       0
>   TCP    127.0.0.1:54323        127.0.0.1:31181        ESTABLISHED     14656
>   TCP    127.0.0.1:54325        127.0.0.1:31181        TIME_WAIT       0
>   TCP    127.0.0.1:54326        127.0.0.1:31181        TIME_WAIT       0
>   TCP    [::1]:5432             [::]:0                 LISTENING       11304
> ```
> 
> 2. 再次执行cargo clean , 同时手动删除当前项目目录下的target/   ;
> 3. cargo build  ;   编译OK
> 
> ```
> PS D:\coding\rustProj\meli> cargo build 
>    Compiling proc-macro2 v1.0.43
>    Compiling unicode-ident v1.0.3
> ......
>    Compiling axum v0.6.0-rc.2                                                                                                                                                                                                          
>    Compiling meli-backend v0.1.0 (D:\coding\rustProj\meli)                                                                                                                                                                             
>     Finished dev [unoptimized + debuginfo] target(s) in 1m 37s      
> ```
> 
> 4. cargo run  如下:
> 
> ```
> PS D:\coding\rustProj\meli> cargo run 
>     Finished dev [unoptimized + debuginfo] target(s) in 0.35s
>      Running `target\debug\meli-backend.exe`
> error: process didn't exit successfully: `target\debug\meli-backend.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
> ```


确认windows下postgresql运行状态,   运行于5432

```
 pg_ctl -D ../data status
pg_ctl: 正在运行服务器进程(PID: 11304)
D:/devkit/pgsql/postgresql-15.1-1-windows-x64-binaries/pgsql/bin/postgres.exe "-D" "../data"
```

**Comment by ariagecheney** [comment]
1. 在cygwin里, 
执行`cargo run ` 
```
# Administrator @ desktop-chy in /d/coding/rustProj/meli [18:42:46]
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target\debug\meli-backend.exe`
error: process didn't exit successfully: `target\debug\meli-backend.exe` (exit code: 3

```


2. 在IDEA的terminal(powershell)里
```
PS D:\coding\rustProj\meli> cargo run                   
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target\debug\meli-backend.exe`
error: process didn't exit successfully: `target\debug\meli-backend.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)


```

**Comment by yez730** [comment]
可以通过.env里的配置连接进数据库吗
试试重启下电脑，然后cargo uninstall/install 重新装下 diesel_cli试试。

**Comment by ariagecheney** [comment]
> 可以通过.env里的配置连接进数据库吗 试试重启下电脑，然后cargo uninstall/install 重新装下 diesel_cli试试。

![image](https://user-images.githubusercontent.com/35078844/203723251-bf485f5d-ba57-45cc-9da0-2a6a863c430b.png)
![image](https://user-images.githubusercontent.com/35078844/203723442-a04675ba-4eaf-4358-9163-f11a910ccf2a.png)
![image](https://user-images.githubusercontent.com/35078844/203723484-b15c441b-e410-466a-8cf5-12a8514c5fb0.png)
如图

**Comment by ariagecheney** [comment]
感觉后端跑起来了,,但是又不完全.

**Comment by ariagecheney** [comment]
> 感觉后端跑起来了,,但是又不完全.

访问的是你的自建域名`PROD_CROSS_ORIGIN=https://ahab.me` 

`DEV_CROSS_ORIGIN=http://127.0.0.1:8080` 无法运行,  
`netstat -ano | findstr 8080` 没有结果

**Comment by ariagecheney** [comment]
> 感觉后端跑起来了,,但是又不完全.

访问的是你的自建域名`PROD_CROSS_ORIGIN=https://ahab.me` 

`DEV_CROSS_ORIGIN=http://127.0.0.1:8080` 无法运行,  
`netstat -ano | findstr 8080` 没有结果

**Comment by yez730** [comment]
clone `https://github.com/yez730/meli-front`，然后`npm i` 和 `npm run dev`，前端就会以127.0.0.1:8080运行。

**Comment by yez730** [comment]
$MELI_ENV=PROD

> 感觉后端跑起来了,,但是又不完全.

就是个最简单的CURD，

**Comment by ariagecheney** [comment]
> clone `https://github.com/yez730/meli-front`，然后`npm i` 和 `npm run dev`，前端就会以127.0.0.1:8080运行。

好的. 我前端也不太会.   哈哈哈哈

**Comment by yez730** [comment]
自己跑一遍，就能了解个大概

**Comment by yez730** [comment]
https://github.com/diesel-rs/diesel/discussions/2947
